<?php
declare(strict_types=1);
/* Private operational view. Set VELARIS_ADMIN_USER and VELARIS_ADMIN_PASSWORD in the web-server environment before enabling it. */
$user = getenv('VELARIS_ADMIN_USER'); $password = getenv('VELARIS_ADMIN_PASSWORD');
if (!$user || !$password) { http_response_code(503); exit('Admin is disabled. Configure VELARIS_ADMIN_USER and VELARIS_ADMIN_PASSWORD in the server environment.'); }
if (!isset($_SERVER['PHP_AUTH_USER']) || !hash_equals($user, $_SERVER['PHP_AUTH_USER']) || !hash_equals($password, $_SERVER['PHP_AUTH_PW'] ?? '')) { header('WWW-Authenticate: Basic realm="Velaris Admin"'); http_response_code(401); exit('Authentication required.'); }
$db = new PDO('sqlite:' . dirname(__DIR__) . '/storage/velaris.sqlite'); $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$db->exec('CREATE TABLE IF NOT EXISTS vehicles (id INTEGER PRIMARY KEY, make TEXT NOT NULL, model TEXT NOT NULL, variant TEXT, year INTEGER, mileage INTEGER, fuel TEXT, transmission TEXT, power INTEGER, body_type TEXT, status TEXT DEFAULT "available", image TEXT, description TEXT, featured INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP)');
$db->exec('CREATE TABLE IF NOT EXISTS leads (id INTEGER PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT, whatsapp TEXT, message TEXT, contact_method TEXT, vehicle_id INTEGER, source TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP)');
$db->exec('CREATE TABLE IF NOT EXISTS dealers (id INTEGER PRIMARY KEY, name TEXT NOT NULL, contact_name TEXT, phone TEXT, email TEXT, country TEXT, internal_notes TEXT)');
$db->exec('CREATE TABLE IF NOT EXISTS vehicle_internal (vehicle_id INTEGER PRIMARY KEY, dealer_id INTEGER, purchase_price_cents INTEGER, target_price_cents INTEGER, commission_cents INTEGER, internal_notes TEXT)');
$vehicles=$db->query('SELECT v.*, d.name dealer, i.purchase_price_cents,i.target_price_cents,i.commission_cents FROM vehicles v LEFT JOIN vehicle_internal i ON i.vehicle_id=v.id LEFT JOIN dealers d ON d.id=i.dealer_id ORDER BY v.created_at DESC')->fetchAll(PDO::FETCH_ASSOC);
$leads=$db->query('SELECT l.*, v.make || " " || v.model AS vehicle FROM leads l LEFT JOIN vehicles v ON v.id=l.vehicle_id ORDER BY l.created_at DESC')->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><meta charset="utf-8"><title>Velaris Admin</title><style>body{margin:0;background:#111;color:#eee;font:14px Arial;padding:40px}h1{color:#ff6a00}table{border-collapse:collapse;width:100%;margin:18px 0 48px;background:#171717}td,th{padding:12px;border:1px solid #333;text-align:left}th{color:#ff6a00}small{color:#999}</style><h1>Velaris Admin</h1><p>Private operational data — do not share this URL or credentials.</p><h2>Inventory</h2><table><tr><th>Vehicle</th><th>Status</th><th>Dealer</th><th>Purchase</th><th>Target</th><th>Commission</th></tr><?php foreach($vehicles as $v): ?><tr><td><?=htmlspecialchars($v['make'].' '.$v['model'].' '.$v['variant'])?></td><td><?=htmlspecialchars($v['status'])?></td><td><?=htmlspecialchars($v['dealer']??'—')?></td><td><?=isset($v['purchase_price_cents'])?'€'.number_format($v['purchase_price_cents']/100,0):'—'?></td><td><?=isset($v['target_price_cents'])?'€'.number_format($v['target_price_cents']/100,0):'—'?></td><td><?=isset($v['commission_cents'])?'€'.number_format($v['commission_cents']/100,0):'—'?></td></tr><?php endforeach ?></table><h2>Latest enquiries</h2><table><tr><th>Received</th><th>Customer</th><th>Vehicle</th><th>Contact</th><th>Message</th></tr><?php foreach($leads as $l): ?><tr><td><?=htmlspecialchars($l['created_at'])?></td><td><?=htmlspecialchars($l['name'])?><br><small><?=htmlspecialchars($l['email'])?></small></td><td><?=htmlspecialchars($l['vehicle']??'General enquiry')?></td><td><?=htmlspecialchars($l['contact_method']??'Email')?> · <?=htmlspecialchars($l['phone']??$l['whatsapp']??'—')?></td><td><?=htmlspecialchars($l['message']??'—')?></td></tr><?php endforeach ?></table>
